//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arks_SystemTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arks_SystemTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filecheck.
        /// </summary>
        public static string button_filecheck {
            get {
                return ResourceManager.GetString("button_filecheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string button_launch {
            get {
                return ResourceManager.GetString("button_launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string button_reset {
            get {
                return ResourceManager.GetString("button_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string button_settings {
            get {
                return ResourceManager.GetString("button_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string button_tools {
            get {
                return ResourceManager.GetString("button_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string button_translate {
            get {
                return ResourceManager.GetString("button_translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep JP enemy names.
        /// </summary>
        public static string check_keep_enemy_jpnames {
            get {
                return ResourceManager.GetString("check_keep_enemy_jpnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep JP Emergency Trial names.
        /// </summary>
        public static string check_keep_et_jpnames {
            get {
                return ResourceManager.GetString("check_keep_et_jpnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean GameGuard at launch.
        /// </summary>
        public static string check_remove_gg_atlaunch {
            get {
                return ResourceManager.GetString("check_remove_gg_atlaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove censorship.
        /// </summary>
        public static string check_rm_censorship {
            get {
                return ResourceManager.GetString("check_rm_censorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string check_translate {
            get {
                return ResourceManager.GetString("check_translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap short_blue_512 {
            get {
                object obj = ResourceManager.GetObject("short_blue_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is up to date.
        /// </summary>
        public static string str_game_uptodate {
            get {
                return ResourceManager.GetString("str_game_uptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string str_path {
            get {
                return ResourceManager.GetString("str_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source server:.
        /// </summary>
        public static string str_update_source {
            get {
                return ResourceManager.GetString("str_update_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arks-System Tool.
        /// </summary>
        public static string title_main_window {
            get {
                return ResourceManager.GetString("title_main_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string title_settings {
            get {
                return ResourceManager.GetString("title_settings", resourceCulture);
            }
        }
    }
}
