//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arks_SystemTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arks_SystemTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filecheck.
        /// </summary>
        public static string button_filecheck {
            get {
                return ResourceManager.GetString("button_filecheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string button_launch {
            get {
                return ResourceManager.GetString("button_launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string button_reset {
            get {
                return ResourceManager.GetString("button_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string button_settings {
            get {
                return ResourceManager.GetString("button_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string button_tools {
            get {
                return ResourceManager.GetString("button_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string button_translate {
            get {
                return ResourceManager.GetString("button_translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep JP enemy names.
        /// </summary>
        public static string check_keep_enemy_jpnames {
            get {
                return ResourceManager.GetString("check_keep_enemy_jpnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep JP Emergency Trial names.
        /// </summary>
        public static string check_keep_et_jpnames {
            get {
                return ResourceManager.GetString("check_keep_et_jpnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean GameGuard at launch.
        /// </summary>
        public static string check_remove_gg_atlaunch {
            get {
                return ResourceManager.GetString("check_remove_gg_atlaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove censorship.
        /// </summary>
        public static string check_rm_censorship {
            get {
                return ResourceManager.GetString("check_rm_censorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string check_translate {
            get {
                return ResourceManager.GetString("check_translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string label_resources {
            get {
                return ResourceManager.GetString("label_resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string label_site {
            get {
                return ResourceManager.GetString("label_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap short_blue_512 {
            get {
                object obj = ResourceManager.GetObject("short_blue_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PSO2&apos;s installation folder..
        /// </summary>
        public static string str_browse_pso2_bin {
            get {
                return ResourceManager.GetString("str_browse_pso2_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string str_checking {
            get {
                return ResourceManager.GetString("str_checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cancelled, please run a filecheck..
        /// </summary>
        public static string str_download_cancelled {
            get {
                return ResourceManager.GetString("str_download_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download has successfully completed..
        /// </summary>
        public static string str_download_completed {
            get {
                return ResourceManager.GetString("str_download_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more files might not have been downloaded correctly.
        ///Please check the log for errors before closing this window..
        /// </summary>
        public static string str_download_error {
            get {
                return ResourceManager.GetString("str_download_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSO2 needs to be installed to continue, rerun the tool if you wish to install PSO2 or when you are able to detect the game folder..
        /// </summary>
        public static string str_exit_no_pso2 {
            get {
                return ResourceManager.GetString("str_exit_no_pso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something might not work.
        ///Force translation version anyway?.
        /// </summary>
        public static string str_force_translation_version {
            get {
                return ResourceManager.GetString("str_force_translation_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phantasy Star Online 2 is out of date, please consider updating..
        /// </summary>
        public static string str_game_out_of_date {
            get {
                return ResourceManager.GetString("str_game_out_of_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phantasy Star Online 2 is up to date..
        /// </summary>
        public static string str_game_up_to_date {
            get {
                return ResourceManager.GetString("str_game_up_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is up to date.
        /// </summary>
        public static string str_game_uptodate {
            get {
                return ResourceManager.GetString("str_game_uptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something might not work.
        ///Launch anyway?.
        /// </summary>
        public static string str_launch_anyway {
            get {
                return ResourceManager.GetString("str_launch_anyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updater found, please reinstall totally Arks-System Tool..
        /// </summary>
        public static string str_no_updater_found {
            get {
                return ResourceManager.GetString("str_no_updater_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string str_path {
            get {
                return ResourceManager.GetString("str_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to install the game in the selected path?.
        /// </summary>
        public static string str_prompt_create_pso2_bin {
            get {
                return ResourceManager.GetString("str_prompt_create_pso2_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update?.
        /// </summary>
        public static string str_prompt_to_update {
            get {
                return ResourceManager.GetString("str_prompt_to_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears PSO2 is already running.\r\nPlease exit the game or reboot..
        /// </summary>
        public static string str_pso2_already_running {
            get {
                return ResourceManager.GetString("str_pso2_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A proper game path could not be found or created.
        ///Click OK to retry or cancel to exit..
        /// </summary>
        public static string str_pso2_bin_not_found {
            get {
                return ResourceManager.GetString("str_pso2_bin_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will close, please launch it again..
        /// </summary>
        public static string str_reset {
            get {
                return ResourceManager.GetString("str_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the &quot;pso2_bin&quot; folder. If the game is not currently installed it will install it..
        /// </summary>
        public static string str_select_create_pso2_bin {
            get {
                return ResourceManager.GetString("str_select_create_pso2_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available for this tool. The updater will update it right now..
        /// </summary>
        public static string str_tool_update_available {
            get {
                return ResourceManager.GetString("str_tool_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the translation version doesn&apos;t match the current game version.
        ///Would you like to update the translation?.
        /// </summary>
        public static string str_translation_missmatch {
            get {
                return ResourceManager.GetString("str_translation_missmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source server:.
        /// </summary>
        public static string str_update_source {
            get {
                return ResourceManager.GetString("str_update_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string title_about {
            get {
                return ResourceManager.GetString("title_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string title_cancelled {
            get {
                return ResourceManager.GetString("title_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string title_download {
            get {
                return ResourceManager.GetString("title_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed.
        /// </summary>
        public static string title_download_completed {
            get {
                return ResourceManager.GetString("title_download_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        public static string title_download_error {
            get {
                return ResourceManager.GetString("title_download_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting.
        /// </summary>
        public static string title_exiting {
            get {
                return ResourceManager.GetString("title_exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filecheck.
        /// </summary>
        public static string title_filecheck {
            get {
                return ResourceManager.GetString("title_filecheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string title_log {
            get {
                return ResourceManager.GetString("title_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arks-System Tool.
        /// </summary>
        public static string title_main_window {
            get {
                return ResourceManager.GetString("title_main_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updater found.
        /// </summary>
        public static string title_no_updater_found {
            get {
                return ResourceManager.GetString("title_no_updater_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phantasy Star Online 2 is already running.
        /// </summary>
        public static string title_pso2_already_running {
            get {
                return ResourceManager.GetString("title_pso2_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game folder not found.
        /// </summary>
        public static string title_pso2_bin_not_found {
            get {
                return ResourceManager.GetString("title_pso2_bin_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string title_reset {
            get {
                return ResourceManager.GetString("title_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string title_settings {
            get {
                return ResourceManager.GetString("title_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arks-System Tool update available.
        /// </summary>
        public static string title_tool_update_available {
            get {
                return ResourceManager.GetString("title_tool_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating translation.
        /// </summary>
        public static string title_translation_download {
            get {
                return ResourceManager.GetString("title_translation_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation update required.
        /// </summary>
        public static string title_translation_update {
            get {
                return ResourceManager.GetString("title_translation_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update required.
        /// </summary>
        public static string title_update_required {
            get {
                return ResourceManager.GetString("title_update_required", resourceCulture);
            }
        }
    }
}
